### ISSUE TITLE
[FEAT] 코드라이언 세션3 실습🦁

### ISSUE THREAD

**Issue by soeunkk** [Likelion-at-SMWU-10th/KimSoEun#4]
## 📌  Feature Issue

코드라이언 "실검에 오르는 세렝게티 동물 테스트 만들기" 실습 코드

## 📝  To-do

- [x] 세렝게티 동물 테스트 메인 기능
- [x] SNS 공유 기능
- [x] 광고 붙이기
- [x] 사이트 검색 가능 및 검색엔진 최적화

**Comment by soeunkk** [comment]
deploy 링크: https://serengetisoeunkk.netlify.app
